dev-oops:
  mcp:
    webhook-url: https://smee.io/hyo7rXKdSHvrrg14 # GitHub Webhook 테스트용 (https://docs.github.com/ko/webhooks/testing-and-troubleshooting-webhooks/testing-webhooks)

spring:
  config:
    activate:
      on-profile: local

jwt:
  secret_key: lnklbdsxjfhruyfidjgjgrjfjfjhfhhh
  access_token_expiration: 1h
  refresh_token_expiration: 3d

cors:
  origin: http://localhost:8080
