spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-secretsmanager:dev/devoops/secrets'
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
